# Generated by Django 4.2.3 on 2023-07-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(default=2, max_length=14),
            preserve_default=False,
        ),
    ]
