# Generated by Django 4.2.3 on 2023-07-26 02:05

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=17)),
                ('manufacturer', models.CharField(max_length=50)),
                ('categorie', models.CharField(choices=[('CC', 'Compact Car'), ('CP', 'Compacte Premium'), ('SC', 'Sedan Coupe'), ('SP', 'Sport Car'), ('SUV', 'Sport Utility Vehicle'), ('LT', 'Light Truck'), ('HDT', 'Heavy Duty Truck'), ('FV', 'Family Van'), ('WV', 'Work Van')], max_length=255)),
                ('manufacture_year', models.DateTimeField()),
                ('model_year', models.DateTimeField()),
                ('mileage', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('G', 'Gasoline'), ('E', 'Ethanol'), ('D', 'Diesel'), ('EV', 'Electric Vehicle')], max_length=255)),
                ('fuel_level', models.CharField(choices=[('E', 'Empety'), ('F', 'Full')], max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
