# Generated by Django 4.2.3 on 2023-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_level',
            field=models.CharField(choices=[('E', 'Empty'), ('F', 'Full')], max_length=255),
        ),
    ]
