# Generated by Django 4.2.3 on 2023-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_fuel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('VACANT', 'VACANT'), ('RENTED', 'RENTED')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='categorie',
            field=models.CharField(choices=[('WORK_VAN', 'WORK VAN')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_level',
            field=models.CharField(choices=[('FULL', 'FULL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('ELECTRIC_VEHICLE', 'ELECTRIC VEHICLE')], max_length=30),
        ),
    ]
