# Generated by Django 4.2.3 on 2023-07-27 16:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import djchoices.choices
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_status_alter_car_categorie_alter_car_fuel_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategorie',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=30, unique=True, verbose_name=djchoices.choices.DjangoChoices)),
                ('value', models.FloatField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcategorie'),
        ),
    ]
