# Generated by Django 4.2.3 on 2023-07-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carcategorie_alter_car_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='VACANT', max_length=10),
        ),
    ]
