# Generated by Django 4.2.3 on 2023-07-28 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_plate',
            field=models.CharField(default=2, max_length=7, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis_number',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='carcategorie',
            name='categorie',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('WORK_VAN', 'WORK VAN')], max_length=30, unique=True),
        ),
    ]
