# Generated by Django 4.2.3 on 2023-07-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_car_plate_alter_car_chassis_number_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_plate',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
