# Generated by Django 4.2.3 on 2023-07-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_car_plate_alter_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_plate',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
