# Generated by Django 4.2.3 on 2023-08-02 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_alter_car_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('days_amount', models.CharField(max_length=10)),
                ('total_price', models.FloatField(default=0)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'CREDIT CARD'), ('DEBIT_CARD', 'DEBIT CARD'), ('BILLET', 'BILLET'), ('PIX', 'PIX'), ('CASH', 'CASH')], max_length=20)),
                ('payment_status', models.CharField(choices=[('DONE', 'DONE'), ('NOT_DONE', 'NOT DONE')], default='NOT_DONE', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
