# Generated by Django 4.2.3 on 2023-09-05 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='users',
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
